<#
.SYNOPSIS
    {{COMPANY_NAME}} — Shared PowerShell module for Fabric deployment.
.DESCRIPTION
    Provides helper functions for deploying the {{COMPANY_NAME}} demo
    to a Microsoft Fabric workspace via REST API and OneLake DFS.
    Generated by Fabric End-to-End Industry Demo Generator.
#>

# ── Module Constants ──
$script:CompanyName   = "{{COMPANY_NAME}}"
$script:IndustryId    = "{{INDUSTRY_ID}}"
$script:WorkspacePrefix = "{{WORKSPACE_PREFIX}}"
$script:BronzeLH      = "{{BRONZE_LAKEHOUSE}}"
$script:SilverLH      = "{{SILVER_LAKEHOUSE}}"
$script:GoldLH         = "{{GOLD_LAKEHOUSE}}"
$script:PipelineName   = "{{PIPELINE_NAME}}"

# ── Token Management ──
function Get-FabricToken {
    [CmdletBinding()]
    param(
        [string]$TenantId = $env:FABRIC_TENANT_ID,
        [string]$ClientId = $env:FABRIC_CLIENT_ID,
        [string]$ClientSecret = $env:FABRIC_CLIENT_SECRET
    )
    $body = @{
        grant_type    = "client_credentials"
        client_id     = $ClientId
        client_secret = $ClientSecret
        scope         = "https://api.fabric.microsoft.com/.default"
    }
    $resp = Invoke-RestMethod -Uri "https://login.microsoftonline.com/$TenantId/oauth2/v2.0/token" -Method Post -Body $body
    return $resp.access_token
}

# ── Fabric REST API Helpers ──
function Invoke-FabricApi {
    [CmdletBinding()]
    param(
        [string]$Token,
        [string]$Method = "GET",
        [string]$Uri,
        [object]$Body
    )
    $headers = @{
        "Authorization" = "Bearer $Token"
        "Content-Type"  = "application/json"
    }
    $params = @{
        Uri     = $Uri
        Method  = $Method
        Headers = $headers
    }
    if ($Body) { $params.Body = ($Body | ConvertTo-Json -Depth 10) }
    Invoke-RestMethod @params
}

function New-FabricItem {
    [CmdletBinding()]
    param(
        [string]$Token,
        [string]$WorkspaceId,
        [string]$DisplayName,
        [string]$Type,
        [string]$Description = ""
    )
    $uri = "https://api.fabric.microsoft.com/v1/workspaces/$WorkspaceId/items"
    $body = @{
        displayName = $DisplayName
        type        = $Type
        description = $Description
    }
    Invoke-FabricApi -Token $Token -Method POST -Uri $uri -Body $body
}

function Get-FabricItem {
    [CmdletBinding()]
    param(
        [string]$Token,
        [string]$WorkspaceId,
        [string]$DisplayName,
        [string]$Type
    )
    $uri = "https://api.fabric.microsoft.com/v1/workspaces/$WorkspaceId/items?type=$Type"
    $items = (Invoke-FabricApi -Token $Token -Uri $uri).value
    $items | Where-Object { $_.displayName -eq $DisplayName }
}

# ── OneLake Upload ──
function Send-ToOneLake {
    [CmdletBinding()]
    param(
        [string]$Token,
        [string]$WorkspaceId,
        [string]$ItemId,
        [string]$LocalPath,
        [string]$RemotePath
    )
    $uri = "https://onelake.dfs.fabric.microsoft.com/$WorkspaceId/$ItemId/$RemotePath"
    $headers = @{
        "Authorization" = "Bearer $Token"
        "x-ms-blob-type" = "BlockBlob"
    }
    $bytes = [System.IO.File]::ReadAllBytes($LocalPath)
    Invoke-RestMethod -Uri $uri -Method PUT -Headers $headers -Body $bytes
}

# ── Lakehouse Creation ──
function New-Lakehouses {
    [CmdletBinding()]
    param(
        [string]$Token,
        [string]$WorkspaceId
    )
    foreach ($lh in @($script:BronzeLH, $script:SilverLH, $script:GoldLH)) {
        $existing = Get-FabricItem -Token $Token -WorkspaceId $WorkspaceId -DisplayName $lh -Type "Lakehouse"
        if (-not $existing) {
            Write-Host "  Creating Lakehouse: $lh" -ForegroundColor Cyan
            New-FabricItem -Token $Token -WorkspaceId $WorkspaceId -DisplayName $lh -Type "Lakehouse"
        } else {
            Write-Host "  Lakehouse exists: $lh" -ForegroundColor Gray
        }
    }
}

Export-ModuleMember -Function Get-FabricToken, Invoke-FabricApi, New-FabricItem, Get-FabricItem, Send-ToOneLake, New-Lakehouses
