// KQL Alert Rule — {{ALERT_NAME}}
// {{COMPANY_NAME}} Eventhouse / {{KQL_DATABASE}}
// Generated by Fabric End-to-End Industry Demo Generator
//
// Severity: {{SEVERITY}}
// Condition: {{CONDITION}}
// Evaluation: every {{EVALUATION_INTERVAL}}

// Alert detection query
let alertThreshold = {{THRESHOLD}};
let lookbackWindow = {{LOOKBACK_WINDOW}};
{{SOURCE_TABLE}}
| where {{TIME_COLUMN}} > ago(lookbackWindow)
| summarize {{AGGREGATION}} by bin({{TIME_COLUMN}}, {{BIN_SIZE}}){{#IF GROUP_BY}}, {{GROUP_BY}}{{/IF}}
| where {{METRIC_COLUMN}} {{OPERATOR}} alertThreshold
| extend AlertName = "{{ALERT_NAME}}"
| extend Severity = "{{SEVERITY}}"
| extend DetectedAt = now()
| project DetectedAt, AlertName, Severity, {{METRIC_COLUMN}}, {{TIME_COLUMN}}{{#IF GROUP_BY}}, {{GROUP_BY}}{{/IF}}
