// {{company_name}} — Hot/Cold Bridge Queries
// Bridges KQL Eventhouse (hot) ↔ Lakehouse (cold)
// Auto-generated by FabricEndtoEnd generator

// ── Cold → Hot: Load historical data from Lakehouse ──
{{#EACH tables}}
// Load {{item.name}} from Lakehouse
.set-or-append {{item.name}} <|
    external_table('{{gold_lakehouse}}_fact_{{item.name}}')
    | where ingestion_time() > ago(30d)

{{/EACH tables}}

// ── Hot → Cold: Export aggregated data back to Lakehouse ──
{{#EACH aggregations}}
// Aggregate {{item.source}} → {{item.name}}
let {{item.name}} = {{item.source}}
    | summarize {{item.aggregation}} by bin({{item.timeColumn}}, {{item.granularity}})
    | order by {{item.timeColumn}} asc;
{{/EACH aggregations}}
