// KQL Create Table — {{TABLE_NAME}}
// {{COMPANY_NAME}} Eventhouse / {{KQL_DATABASE}}
// Generated by Fabric End-to-End Industry Demo Generator

.create-merge table {{TABLE_NAME}} (
{{#EACH COLUMNS}}
    {{COLUMN_NAME}}: {{KQL_TYPE}}{{#IF NOT_LAST}},{{/IF}}
{{/EACH}}
)

// Ingestion mapping
.create-or-alter table {{TABLE_NAME}} ingestion json mapping '{{TABLE_NAME}}_mapping'
```
[
{{#EACH COLUMNS}}
    {"column": "{{COLUMN_NAME}}", "Properties": {"Path": "$.{{COLUMN_NAME}}"}}{{#IF NOT_LAST}},{{/IF}}
{{/EACH}}
]
```

// Retention policy
.alter-merge table {{TABLE_NAME}} policy retention softdelete = {{RETENTION_DAYS}}d recoverability = enabled

// Caching policy
.alter-merge table {{TABLE_NAME}} policy caching hot = {{CACHING_DAYS}}d
