// {{company_name}} — Eventhouse Definition
// Auto-generated by FabricEndtoEnd generator
//
// KQL Database: {{kql_database_name}}
// Streams: {{stream_count}}

{{#EACH tables}}
// Table: {{item.name}}
.create-merge table {{item.name}} (
{{#EACH item.columns}}
    {{item.name}}: {{item.type}}{{item.comma}}
{{/EACH item.columns}}
)
{{/EACH tables}}
