// {{company_name}} — KQL Database Setup
// Auto-generated by FabricEndtoEnd generator

// Retention policy
.alter-merge database policy retention softdelete = 365d

{{#EACH tables}}
// ── {{item.name}} ──
.create-merge table {{item.name}} (
{{#EACH item.columns}}
    {{item.name}}: {{item.type}}{{item.comma}}
{{/EACH item.columns}}
)

// Ingestion mapping
.create-or-alter table {{item.name}} ingestion json mapping '{{item.name}}_mapping'
```
[
{{#EACH item.columns}}
    {"column": "{{item.name}}", "path": "$.{{item.name}}", "datatype": "{{item.type}}"}{{item.comma}}
{{/EACH item.columns}}
]
```

{{/EACH tables}}

{{#EACH functions}}
// Function: {{item.name}}
.create-or-alter function {{item.name}}() {
    {{item.body}}
}
{{/EACH functions}}
