// KQL Materialized View — {{VIEW_NAME}}
// {{COMPANY_NAME}} Eventhouse / {{KQL_DATABASE}}
// Generated by Fabric End-to-End Industry Demo Generator
//
// Materialized views provide pre-aggregated real-time data
// for dashboard queries with sub-second response times.

.create-or-alter materialized-view with (backfill=true) {{VIEW_NAME}} on table {{SOURCE_TABLE}}
{
    {{SOURCE_TABLE}}
    | summarize {{AGGREGATION}}
      by bin({{TIME_COLUMN}}, {{BIN_SIZE}}), {{GROUP_BY_COLUMNS}}
}
