/// {{company_name}} — Semantic Model
/// Auto-generated by FabricEndtoEnd generator

model Model
	culture: en-US
	defaultPowerBIDataSourceVersion: powerBI_V3
	sourceQueryCulture: en-US

	annotation PBI_QueryOrder = {{table_order}}
