/// Relationship: {{from_table}}.{{from_column}} → {{to_table}}.{{to_column}}
/// Auto-generated by FabricEndtoEnd generator

relationship {{relationship_id}}
	fromColumn: '{{from_table}}'.'{{from_column}}'
	toColumn: '{{to_table}}'.'{{to_column}}'
	{{#IF is_inactive}}
	isActive: false
	{{/IF is_inactive}}
