/// Table: {{table_name}}
/// Schema: {{table_schema}}
/// Auto-generated by FabricEndtoEnd generator

table '{{table_name}}'
	lineageTag: {{lineage_tag}}

{{#EACH columns}}
	column '{{item.name}}'
		dataType: {{item.dataType}}
		{{#IF item.isKey}}
		isKey
		{{/IF item.isKey}}
		{{#IF item.formatString}}
		formatString: {{item.formatString}}
		{{/IF item.formatString}}
		lineageTag: {{item.lineageTag}}
		summarizeBy: {{item.summarizeBy|none}}
		sourceColumn: {{item.name}}

{{/EACH columns}}

{{#EACH measures}}
	measure '{{item.name}}'
		= {{item.expression}}
		formatString: {{item.formatString}}
		{{#IF item.displayFolder}}
		displayFolder: {{item.displayFolder}}
		{{/IF item.displayFolder}}
		lineageTag: {{item.lineageTag}}

{{/EACH measures}}

	partition '{{table_name}}' = entity
		mode: directLake
		source
			entityName: {{table_name}}
			schemaName: {{partition_schema}}
			expressionSource: DatabaseQuery
