# Fabric notebook source
# {{COMPANY_NAME}} — NB04 Forecasting (Holt-Winters + MLflow)
# Generated by Fabric End-to-End Industry Demo Generator

# METADATA ********************
# META {
#   "kernel_info": { "name": "synapse_pyspark" },
#   "dependencies": { "lakehouse": { "default_lakehouse_name": "{{GOLD_LAKEHOUSE}}" } }
# }

# CELL ********************
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, lit, to_date, year, month, dayofmonth
import json, math

spark = SparkSession.builder.getOrCreate()

GOLD = "{{GOLD_LAKEHOUSE}}"
FORECAST_HORIZON = {{FORECAST_HORIZON}}
CONFIDENCE_LEVEL = {{CONFIDENCE_LEVEL}}
SEASONAL_PERIODS = {{SEASONAL_PERIODS}}

print(f"NB04 — {{COMPANY_NAME}} Forecasting")
print(f"  Gold Lakehouse : {GOLD}")
print(f"  Horizon        : {FORECAST_HORIZON} periods")
print(f"  Seasonality    : {SEASONAL_PERIODS} periods")

# CELL ********************
# ── Holt-Winters Implementation (stdlib only — no statsmodels/prophet) ──

def holt_winters_forecast(series: list[float], horizon: int,
                          alpha: float = {{ALPHA}}, beta: float = {{BETA}},
                          gamma: float = {{GAMMA}},
                          seasonal_periods: int = {{SEASONAL_PERIODS}}) -> list[float]:
    """Additive Holt-Winters triple exponential smoothing."""
    n = len(series)
    if n < 2 * seasonal_periods:
        # Fallback: naive seasonal repeat
        return [series[i % n] for i in range(n, n + horizon)]

    # Initialize level, trend, seasonal
    level = sum(series[:seasonal_periods]) / seasonal_periods
    trend = sum(series[seasonal_periods + i] - series[i]
                for i in range(seasonal_periods)) / (seasonal_periods ** 2)
    seasonal = [series[i] - level for i in range(seasonal_periods)]

    # Smooth
    levels, trends, seasonals = [level], [trend], seasonal[:]
    for i in range(n):
        s_idx = i % seasonal_periods
        if i == 0:
            continue
        val = series[i]
        new_level = alpha * (val - seasonals[s_idx]) + (1 - alpha) * (levels[-1] + trends[-1])
        new_trend = beta * (new_level - levels[-1]) + (1 - beta) * trends[-1]
        seasonals[s_idx] = gamma * (val - new_level) + (1 - gamma) * seasonals[s_idx]
        levels.append(new_level)
        trends.append(new_trend)

    # Forecast
    forecasts = []
    for h in range(1, horizon + 1):
        s_idx = (n + h - 1) % seasonal_periods
        forecasts.append(levels[-1] + h * trends[-1] + seasonals[s_idx])
    return forecasts

# CELL ********************
# ── MLflow Experiment Tracking ──

try:
    import mlflow
    mlflow.set_experiment("/{{COMPANY_NAME}}/Forecasting")
    USE_MLFLOW = True
    print("MLflow tracking enabled")
except ImportError:
    USE_MLFLOW = False
    print("MLflow not available — metrics logged to console only")

# CELL ********************
# ── Run Forecast Models ──
{{#EACH FORECAST_MODELS}}
# ── Model: {{MODEL_NAME}} ──
print(f"\n▶ Running forecast: {{MODEL_NAME}}")

source_df = spark.sql("SELECT * FROM {{GOLD_LAKEHOUSE}}.{{SOURCE_TABLE}}")
# Aggregate to time grain
ts_df = (source_df
    .groupBy("{{DATE_COLUMN}}")
    .agg({{"{{VALUE_COLUMN}}": "sum"}})
    .orderBy("{{DATE_COLUMN}}")
)
values = [row[0] for row in ts_df.select(f"sum({{VALUE_COLUMN}})").collect()]

forecast = holt_winters_forecast(values, FORECAST_HORIZON)
print(f"  Input points: {len(values)}, Forecast points: {len(forecast)}")

# Calculate accuracy metrics on last-period holdout
if len(values) > FORECAST_HORIZON:
    holdout = values[-FORECAST_HORIZON:]
    backcast = holt_winters_forecast(values[:-FORECAST_HORIZON], FORECAST_HORIZON)
    mae = sum(abs(a - b) for a, b in zip(holdout, backcast)) / FORECAST_HORIZON
    rmse = math.sqrt(sum((a - b)**2 for a, b in zip(holdout, backcast)) / FORECAST_HORIZON)
    mape = sum(abs((a - b) / a) if a != 0 else 0 for a, b in zip(holdout, backcast)) / FORECAST_HORIZON * 100
    print(f"  MAE={mae:.2f}  RMSE={rmse:.2f}  MAPE={mape:.1f}%")

    if USE_MLFLOW:
        with mlflow.start_run(run_name="{{MODEL_NAME}}"):
            mlflow.log_param("model", "HoltWinters")
            mlflow.log_param("horizon", FORECAST_HORIZON)
            mlflow.log_metric("mae", mae)
            mlflow.log_metric("rmse", rmse)
            mlflow.log_metric("mape", mape)

# Write forecast to Gold
forecast_rows = [(i + 1, v) for i, v in enumerate(forecast)]
forecast_spark = spark.createDataFrame(forecast_rows, ["Period", "Forecast"])
forecast_spark.write.mode("overwrite").saveAsTable(f"{GOLD}.{{OUTPUT_TABLE}}")
print(f"  → Written to {GOLD}.{{OUTPUT_TABLE}}")
{{/EACH}}

# CELL ********************
print("\n✅ NB04 Forecasting complete — all models processed.")
