# Fabric notebook source
# {{COMPANY_NAME}} — NB05 Transactional Analytics (HTAP Event Simulator)
# Generated by Fabric End-to-End Industry Demo Generator

# METADATA ********************
# META {
#   "kernel_info": { "name": "synapse_pyspark" },
#   "dependencies": { "lakehouse": { "default_lakehouse_name": "{{GOLD_LAKEHOUSE}}" } }
# }

# CELL ********************
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, current_timestamp, lit, rand, expr
from pyspark.sql.types import StructType, StructField, StringType, FloatType, TimestampType, IntegerType
import json, uuid, random, time
from datetime import datetime, timedelta

spark = SparkSession.builder.getOrCreate()

GOLD = "{{GOLD_LAKEHOUSE}}"
KQL_DB = "{{KQL_DATABASE}}"
EVENTHOUSE = "{{EVENTHOUSE_NAME}}"

print(f"NB05 — {{COMPANY_NAME}} Transactional Analytics (HTAP)")
print(f"  Gold Lakehouse : {GOLD}")
print(f"  KQL Database   : {KQL_DB}")
print(f"  Eventhouse     : {EVENTHOUSE}")

# CELL ********************
# ── Event Stream Schemas ──
{{#EACH EVENT_STREAMS}}
# Schema: {{STREAM_NAME}}
schema_{{STREAM_NAME}} = StructType([
{{#EACH COLUMNS}}
    StructField("{{COLUMN_NAME}}", {{SPARK_TYPE}}, True),
{{/EACH}}
])
{{/EACH}}

# CELL ********************
# ── Simulated Event Generator ──

def generate_events(stream_name: str, schema: StructType, count: int = 1000) -> list[dict]:
    """Generate simulated events for a stream."""
    events = []
    base_time = datetime.utcnow() - timedelta(hours=1)
    for i in range(count):
        event = {}
        for field in schema.fields:
            if field.name.lower() in ("eventid", "id"):
                event[field.name] = str(uuid.uuid4())
            elif field.name.lower() in ("timestamp", "eventtime"):
                event[field.name] = base_time + timedelta(seconds=i * 3.6)
            elif isinstance(field.dataType, StringType):
                event[field.name] = f"{stream_name}_val_{random.randint(1, 100)}"
            elif isinstance(field.dataType, FloatType):
                event[field.name] = round(random.uniform(0, 1000), 2)
            elif isinstance(field.dataType, IntegerType):
                event[field.name] = random.randint(1, 500)
            else:
                event[field.name] = None
        events.append(event)
    return events

# CELL ********************
# ── Generate and Write Events ──
{{#EACH EVENT_STREAMS}}
print(f"\n▶ Generating events: {{STREAM_NAME}} ({{EVENTS_PER_SECOND}} eps simulation)")

events_{{STREAM_NAME}} = generate_events("{{STREAM_NAME}}", schema_{{STREAM_NAME}}, count={{BATCH_SIZE}})
df_{{STREAM_NAME}} = spark.createDataFrame(events_{{STREAM_NAME}}, schema_{{STREAM_NAME}})

# Write to Lakehouse (cold path)
df_{{STREAM_NAME}}.write.mode("append").saveAsTable(f"{GOLD}.events_{{STREAM_NAME}}")
print(f"  → {len(events_{{STREAM_NAME}})} events written to {GOLD}.events_{{STREAM_NAME}}")
{{/EACH}}

# CELL ********************
# ── Hot-Cold Bridge Queries ──
# These queries join Eventhouse (hot) data with Lakehouse (cold) data
# for unified analytics across real-time and historical data.

{{#EACH BRIDGE_QUERIES}}
print(f"\n▶ Bridge query: {{QUERY_NAME}}")
bridge_sql = """
{{QUERY_SQL}}
"""
try:
    bridge_df = spark.sql(bridge_sql)
    bridge_df.show(5)
except Exception as e:
    print(f"  Bridge query skipped (Eventhouse not connected): {e}")
{{/EACH}}

# CELL ********************
print("\n✅ NB05 Transactional Analytics complete — events generated, bridge queries executed.")
